--- 
- hosts: mywebservers 
  become: yes 
  tasks:
  - name: i want to install java on ubuntu
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present 
    when: ansible_os_family=="debian"


  - name: install java on redHat nodes
    apt:
      name: "{{myjavapackonRedHat}}"
      state: present
    when: ansible_os_family=="RedHat"
