--- 
- hosts: mywebservers 
  become: yes 
  tasks: 
  - name: install webserver on ubuntu nodes 
    apt: 
      name: "{{mywebpackonubuntu}}"
      state: present 
    when: ansible_os_family =="Debian" 


  - name: install webserver on RedHat nodes 
    yum: 
      name: "{{mywebpackonRedHat}}"
      state: present 
    when: ansible_os_family =="RedHat"  

  - name: i want start webserver on RedHat nodes 
    service: 
      name: "{{mywebpackonRedHat}}"
      state: started 
    when: ansible_os_family =="RedHat" 









         